// Generated by CoffeeScript 1.8.0
var boot;

boot = {
  preload: function() {
    return game.load.image('progressBar', 'assets/progressBar.png');
  },
  create: function() {
    game.stage.backgroundColor = '#444';
    game.physics.startSystem(Phaser.Physics.ARCADE);
    return game.state.start('load');
  }
};
