// Generated by CoffeeScript 1.8.0
var game;

game = new Phaser.Game(1024, 640, Phaser.AUTO, 'game');

game.global = {
  score: 0
};

game.state.add('boot', boot);

game.state.add('load', load);

game.state.add('menu', menu);

game.state.add('play', play);

game.state.start('boot');
