// Generated by CoffeeScript 1.8.0
var load;

load = {
  preload: function() {
    var loadingLabel, progressBar;
    loadingLabel = game.add.text(game.world.centerX, 150, 'Loading...', {
      font: '50px Arial',
      fill: '#FFF'
    });
    loadingLabel.anchor.setTo(0.5, 0.5);
    progressBar = game.add.sprite(game.world.centerX, 200, 'progressBar');
    progressBar.anchor.setTo(0.5, 0.5);
    game.load.setPreloadSprite(progressBar);
    return game.load.spritesheet('mute', 'assets/muteButton.png', 28, 22);
  },
  create: function() {
    return game.state.start('menu');
  }
};
